name: Next.js Login CI

on:
  push:
https://github.com/cadumega/login-app/actions/new    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build Next.js app
      run: npm run build
      
    - name: Run Cypress tests
      uses: cypress-io/github-action@v6
      with:
        build: npm run build
        start: npm start
        wait-on: 'http://localhost:3000'
        
    - name: Archive test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: cypress-results
        path: |
          cypress/videos
          cypress/screenshots
        retention-days: 7