name: Next.js Login Tests

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Clear npm cache
      run: npm cache clean --force
        
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build Next.js app
      run: npm run build

    - name: List directories
      run: ls -al
      
    - name: Install Cypress dependencies
      working-directory: ./tests
      run: npm ci

    - name: Start Next.js server (background)
      run: npm run start &
      working-directory: ./
        
    - name: Run Cypress tests
      uses: cypress-io/github-action@v6
      with:
        working-directory: ./tests
        wait-on: 'http://localhost:3000'
        spec: "**/*.cy.{js,jsx,ts,tsx}"
        browser: chrome

    - name: Upload test screenshots if tests fail
      uses: actions/upload-artifact@v3
      if: failure()
      with:
          name: cypress-screenshots
          path: cypress/screenshots
          
    - name: Upload test videos
      uses: actions/upload-artifact@v3
      if: always()
      with:
          name: cypress-videos
          path: cypress/videos
