name: Next.js Login Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build Next.js app
      run: npm run build
      
    - name: Install Cypress
      run: npm install cypress --save-dev
      
    - name: Run Cypress tests
      uses: cypress-io/github-action@v6
      with:
        working-directory: ./login-app
        start: npm start
        run: npx cypress run
        wait-on: 'http://localhost:3000'
        browser: chrome

    - name: Upload Cypress results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: cypress-results
        path: |
          cypress/videos
          cypress/screenshots
