name: Next.js Login Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build Next.js app
      run: npm run build
      
    - name: Start Next.js server
      run: npm start &
      
    - name: Wait for server to start
      run: |
        npx wait-on http://localhost:3000 --timeout 60000 || (echo "Server failed to start" && exit 1)
      
    - name: Run Cypress tests directly
      run: npx cypress run
      
    - name: Upload Cypress results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: cypress-results
        path: |
          cypress/videos
          cypress/screenshots
